import styles from "./index.module.css";
import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>jugadu</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <h1 className={styles.title}>
            build <span className={styles.pinkSpan}>jugadu</span>
          </h1>
          <div className={styles.subtitle}>
            building apps that <span className={styles.emphasize}>don&apos;t</span> scale
          </div>
          <div className={styles.whiteText}><a href="https://twitter.com/buildjugadu" className={styles.link}>twitter</a>; <a href="mailto:hello@jugadu.co" className={styles.link}>email</a></div>
        </div>
      </main>
    </>
  );
};

export default Home;
